initial

diff --git a/utils/tests/gitlab-ci-code-linting.yml b/utils/tests/gitlab-ci-code-linting.yml
--- a/utils/tests/gitlab-ci-code-linting.yml
+++ b/utils/tests/gitlab-ci-code-linting.yml
@@ -3,111 +3,155 @@
 # Contains jobs to check the ns-3 coding style and perform lint checking.
 
 # Clang-format
-check-style-clang-format:
-  stage: code-linting
-  image: ubuntu:latest
+.check-style-clang-format:
+  stage: .pre
+  image: ubuntu:rolling
   before_script:
     - apt update
     - DEBIAN_FRONTEND=noninteractive apt install -y
       python3
-      clang-format-14
+      clang-format-$CLANG_FORMAT_VERSION
   script:
-    - python3 utils/check-style-clang-format.py .
+    - python3 utils/check-style-clang-format.py --verbose .
   timeout: 1h
+  interruptible: true
+
+check-style-clang-format-17:
+  extends: .check-style-clang-format
+  variables:
+    CLANG_FORMAT_VERSION: 17
+
+check-style-clang-format-16:
+  extends: .check-style-clang-format
+  variables:
+    CLANG_FORMAT_VERSION: 16
+
+check-style-clang-format-15:
+  extends: .check-style-clang-format
+  variables:
+    CLANG_FORMAT_VERSION: 15
+
+check-style-clang-format-14:
+  extends: .check-style-clang-format
+  variables:
+    CLANG_FORMAT_VERSION: 14
 
 # Clang-tidy
-.base-clang-tidy:
+clang-tidy-17:
   stage: code-linting
-  image: ubuntu:latest
+  image: ubuntu:rolling
   variables:
     MPI_CI: 1
     CLANG_TIDY_OUTPUT: clang-tidy-output.log
+    FILES_CHANGED: git-diff-name-only.log
   before_script:
     - apt update
     - DEBIAN_FRONTEND=noninteractive apt install -y
       clang cmake
-      clang-tidy clang-tidy-14
-      python3 python3-pip
+      clang-tidy clang-tidy-17
       libboost-all-dev libeigen3-dev libgtk-3-dev libopenmpi-dev libsqlite3-dev
       gsl-bin libgsl-dev libgsl27
       git ssh
-    - pip3 install cppyy
     - ./ns3 configure -d debug
       --enable-clang-tidy
       --enable-examples --enable-tests --enable-asserts
-      --enable-mpi --enable-python-bindings
+      --enable-mpi
+  script:
+    - if (git remote | grep -qw upstream) ; then
+      git remote remove upstream ;
+      fi
+    - git remote add -t $CI_DEFAULT_BRANCH --no-tags -f upstream https://gitlab.com/nsnam/ns-3-dev.git
+    - git diff --name-only upstream/$CI_DEFAULT_BRANCH > $FILES_CHANGED
+
+    # Run full clang-tidy in the following cases: 1) default branch, 2) ".clang-tidy" file changed
+    # Run clang-tidy-diff in the opposite cases.
+    # File paths generated by git diff are relative to the working tree. Therefore, iregex should only contain paths relative to the working tree.
+    - if [[ $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]] || (grep -q ".clang-tidy" $FILES_CHANGED) ; then
+      echo "Running full clang-tidy" ;
+      run-clang-tidy-17 -p cmake-cache/ -quiet
+      1> $CLANG_TIDY_OUTPUT
+      2> /dev/null ;
+      else
+      echo "Running clang-tidy-diff" ;
+      git diff -U0 upstream/$CI_DEFAULT_BRANCH |
+      clang-tidy-diff-17.py -path cmake-cache/ -p1 -quiet -use-color
+      -iregex "(contrib|examples|src|scratch|utils)\/.+\.(cpp|cc|cxx|h|hpp)"
+      1> $CLANG_TIDY_OUTPUT
+      2> /dev/null ;
+      fi
+
+    # Check job results
+    - (! egrep -v "file not found \[clang-diagnostic-error\]" $CLANG_TIDY_OUTPUT | egrep -A3 "error:|warning:|note:")
+    - echo "No clang-tidy errors found"
+  dependencies: []
   artifacts:
     paths:
       - $CLANG_TIDY_OUTPUT
     when: on_failure
+  interruptible: true
   timeout: 3h
-
-clang-tidy:
-  extends: .base-clang-tidy
-  rules:
-    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
-      when: never
-    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
-      when: on_success
-    - changes:
-        paths:
-          - .clang-tidy
-        compare_to: master
-      when: on_success
-  script:
-    - run-clang-tidy-14 -p cmake-cache/ -quiet
-      1> $CLANG_TIDY_OUTPUT
-      2> /dev/null
-    - (! egrep -A 3 "error:|warning:|note:" $CLANG_TIDY_OUTPUT)
-    - echo "No clang-tidy errors found"
-
-clang-tidy-diff:
-  extends: .base-clang-tidy
-  rules:
-    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
-      when: never
-    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
-      when: never
-    - changes:
-        paths:
-          - .clang-tidy
-        compare_to: master
-      when: never
-    - when: on_success
-  script:
-    - git remote add upstream https://gitlab.com/nsnam/ns-3-dev.git
-    - git fetch upstream master
-    # File paths generated by git diff are relative to the working tree. Therefore, iregex should only contain paths relative to the working tree.
-    - git diff -U0 upstream/master |
-      clang-tidy-diff-14.py -path cmake-cache/ -p1 -quiet -use-color
-      -iregex "(contrib|examples|src|scratch|utils)\/.+\.(cpp|cc|cxx|c|h|hpp)"
-      1> $CLANG_TIDY_OUTPUT
-      2> /dev/null
-    - if egrep -A 3 "file not found \[clang-diagnostic-error\]" $CLANG_TIDY_OUTPUT ; then
-      echo "Clang-tidy could not find the above files. Running a full clang-tidy check." ;
-      run-clang-tidy-14 -p cmake-cache/ -quiet
-      1> $CLANG_TIDY_OUTPUT
-      2> /dev/null ;
-      fi
-    - (! egrep -A 3 "error:|warning:|note:" $CLANG_TIDY_OUTPUT)
-    - echo "No clang-tidy errors found"
 
 # Emacs line
 emacs-line:
-  stage: code-linting
+  stage: .pre
   image: ubuntu:latest
   script:
-    - (! grep -rn --include="*.h" --include="*.cc" "c-file-style:\"gnu\"" ) ||
-      (echo "Found Emacs lines on the above C++ files" && exit 1)
-    - echo "No Emacs lines found on C++ files"
+    - if ( egrep -rn --include="*.h" --include="*.cc" --include="*.c" --include="*.py" --include="*.rst" "c-file-style:|py-indent-offset:" ) ; then
+      echo "Found Emacs lines on the above C/C++, Python and RST files" ;
+      exit 1 ;
+      else
+      echo "No Emacs lines found on C/C++, Python and RST files" ;
+      exit 0 ;
+      fi
   timeout: 1h
+  interruptible: true
 
 # Spell checking
 spell-check:
-  stage: code-linting
+  stage: .pre
   image: python:latest
   before_script:
     - pip install codespell
   script:
-    - codespell ./
+    # Get commit messages
+    - if (git remote | grep -qw upstream) ; then
+      git remote remove upstream ;
+      fi
+    - git remote add -t $CI_DEFAULT_BRANCH --no-tags -f upstream https://gitlab.com/nsnam/ns-3-dev.git
+
+    - git log --pretty=%B HEAD...upstream/$CI_DEFAULT_BRANCH ^upstream/$CI_DEFAULT_BRANCH > git_messages.txt
+    # Check source code and commit messages
+    - codespell -f -C0 ./
   timeout: 1h
+  interruptible: true
+
+# Check cmake format
+cmake-format:
+  stage: .pre
+  image: python:latest
+  before_script:
+    - pip install pyyaml cmake cmake-format ninja
+  script:
+    - ./ns3 configure --enable-modules=core
+    - ./ns3 build cmake-format-check
+  timeout: 1h
+  interruptible: true
+
+# Check Python format
+.python-format:
+  stage: .pre
+  before_script:
+    - pip install black isort
+  script:
+    - black --check .
+    - isort --check .
+  timeout: 1h
+  interruptible: true
+
+python-format-latest:
+  extends: .python-format
+  image: python:latest
+
+python-format-3.6:
+  extends: .python-format
+  image: python:3.6
